language: node_js

node_js: '8'

sudo: required
addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules
  - build

script:
- yarn lint
- yarn test
- yarn build

before_deploy: ls -al build
deploy:
  provider: surge
  project: ./build/
  domain: brc-algolia-appstore.surge.sh
  skip_cleanup: true
  on:
    tags: true
    repo: baptooo/algolia-appstore